server:
  port: 8761

spring:
  security:
    user:
      name: moral
      password: moral
  application:
    name: moral-eureka
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: moral-eureka
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 4000
    enable-self-preservation: false
    renewal-percent-threshold: 0.9

management:
  endpoints:
    web:
      exposure:
        include: '*'